### ISSUE TITLE
calls table timestamps have different timezones?

### ISSUE THREAD

**Issue by akhrail1996** [getsince/test3#428]
![image](https://user-images.githubusercontent.com/16062322/144170056-cf3baf85-c840-46fc-824f-e470b6b52d5f.png)

**Comment by ruslandoga** [comment]
`inserted_at` is `timestamp` or in elixir terms, [`NaiveDateTime`](https://hexdocs.pm/elixir/NaiveDateTime.html) and retains a bit of ambiguity in what TZ it is. By convention, it's UTC (or rather GMT since UTC is not a timezone ...), but tabpleplus doesn't know about it and renders the timestamp as is.

`ended_at` is `timestamptz` or [`DateTime`](https://hexdocs.pm/elixir/DateTime.html) and UTC (or rather `GMT+0`) is its frame of reference, that's why tableplus shows the `+08` offset. To be a bit more clear, `ended_at` is stored as (for the top row) as `2021-09-23 22:33:51+00` and tableplus renders it as `2021-09-24 06:33:51+08` because it knows that `ended_at` is `+00` and your laptop's TZ is `+08`.

`inserted_at` is `timestamp` due to backwards compatibility.

**Comment by akhrail1996** [comment]
thanks! then closing
